### ISSUE TITLE
Error "Unknown column '$1' in 'field list'" when try to run migrator for mysql

### ISSUE THREAD

**Issue by shandak** [iamsauravsharma/sqlx_migrator#12]
`$1` or `$2` do not support in mysql https://github.com/iamsauravsharma/sqlx_migrator/blob/master/src/migrator.rs#L676 instead should be used `?`

**Comment by iamsauravsharma** [comment]
PR #13 fixes issue related to mysql. I will release new version after adding test to CI. You can use latest master version. Beware, latest master have changed trait name.

**Comment by shandak** [comment]
Is there a way to execute multiple queries per one migration? Looks like `connection: &mut MySqlConnection` is once borrowing per the first query and can't be used anymore...

**Comment by iamsauravsharma** [comment]
You can use `.execute(&mut *connection)` instead of `.execute(connection)`

**Comment by shandak** [comment]
> You can use `.execute(&mut *connection)` instead of `.execute(connection)`

This is what I wanted, many thanks!!!
